{{- if and .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-instances
  namespace: monitoring
  labels:
    release: prometheus
    {{- with .Values.monitoring.servicemonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.servicemonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.servicemonitor.scrapeTimeout }}
{{- end }} 