apiVersion: v1
kind: Service
metadata:
  name: redis-operator-metrics-service
  namespace: client-yazio-techtest-system
  labels:
    control-plane: controller-manager
spec:
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: controller-manager