apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-instances
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s