# This rule is not used by the project client-yazio-techtest itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cache.com.yazio.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: client-yazio-techtest
    app.kubernetes.io/managed-by: kustomize
  name: redis-admin-role
rules:
- apiGroups:
  - cache.com.yazio
  resources:
  - redis
  verbs:
  - '*'
- apiGroups:
  - cache.com.yazio
  resources:
  - redis/status
  verbs:
  - get
